version: 2
jobs:
  build_and_deploy:
    working_directory: /home/presto/presto
    environment:
      - PLAZMA_ENV: circle_test
      - RUN_SUBTREE_TEST: true
      - MAVEN_OPTS: -Xmx4g -Xms4g
      - _JAVA_OPTIONS: -Xmx4g -Xms4g -XX:ReservedCodeCacheSize=300M -XX:MaxPermSize=300M -XX:InitiatingHeapOccupancyPercent=30
      - MAVEN_USER_HOME: /home/presto/.m2
      - JAVA_HOME: /home/presto/.java
    docker:
      - image: 523683666290.dkr.ecr.us-east-1.amazonaws.com/td-build:2019-07-01
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Setup non-priviledged user (presto)
          command: |
            apt-get update
            apt-get install -y sudo
            useradd -m presto
            chown -R presto /home/presto/presto
            mkdir /home/presto/.m2
            chown -R presto /home/presto/.m2

      - run:
          name: Install JDK
          command: |
            if [[ -e "${JAVA_HOME}/bin/java" ]]; then
                echo "Detected JDK at ${JAVA_HOME}." 1>&2
                "${JAVA_HOME}/bin/java" -version 1>&2
            else
                mkdir -p "${JAVA_HOME}"
                curl -L -C - https://corretto.aws/downloads/resources/11.0.9.12.1/amazon-corretto-11.0.9.12.1-linux-x64.tar.gz | tar zxvf - -C "${JAVA_HOME}" --strip-components 1
                [[ -e "${JAVA_HOME}/bin/java" ]]
            fi

      - restore_cache:
          key: presto-{{ checksum "pom.xml" }}

      - run:
          name: Bundler
          command: |
            gem install bundler
            bundle install

      - run:
          name: Build presto
          command: |
            # Assign a unique version number to the modules
            sudo -E -u presto rake update-pom
            # Run mvn test-compile here to cache the compile-time dependencies
            sudo -E -u presto bundle exec rake compile

      - run:
          name: Test presto
          command: |
            # Run mvn test-compile here to cache the compile-time dependencies
            sudo -E -u presto bundle exec rake test

      - save_cache:
          paths:
            - /home/presto/.m2
            - /root/.m2
          key: presto-{{ checksum "pom.xml" }}

      - run:
          name: deploy
          command: |
            sudo -E -u presto bundle exec rake deploy
workflows:
  version: 2
  build_and_integration:
    jobs:
      - build_and_deploy:
          filters:
            tags:
              only: /.*/

