---
version: 2
aliases:
  - &install_jdk
    name: Install JDK
    command: |
      mkdir -p "${JAVA_HOME}"
      curl -L -C - https://corretto.aws/downloads/resources/11.0.8.10.1/amazon-corretto-11.0.8.10.1-linux-x64.tar.gz | tar zxvf - -C "${JAVA_HOME}" --strip-components 1
      [[ -e "${JAVA_HOME}/bin/java" ]]

jobs:
  build_and_deploy:
    working_directory: /home/presto/presto
    environment:
      - PLAZMA_ENV: circle_test
      - RUN_SUBTREE_TEST: true
      - MAVEN_OPTS: -Xmx4g -Xms4g
      - _JAVA_OPTIONS: -Xmx4g -Xms4g -XX:ReservedCodeCacheSize=300M -XX:MaxPermSize=300M -XX:InitiatingHeapOccupancyPercent=30
      - RUBY_VERSION: 2.4.1
      - MAVEN_USER_HOME: /home/presto/.m2
      - JAVA_HOME: /home/presto/.java
    docker:
      - image: 523683666290.dkr.ecr.us-east-1.amazonaws.com/td-build:2021-07-06
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Setup non-priviledged user (presto)
          command: |
            apt-get update
            apt-get install -y sudo
            useradd -m presto
            chown -R presto /home/presto/presto
            mkdir /home/presto/.m2
            chown -R presto /home/presto/.m2

      - restore_cache:
          key: presto-{{ checksum "pom.xml" }}

      - run: *install_jdk

      - run:
          name: Build presto
          command: |
            # Exclude unnecessary modules from pom.xml
            rake update-pom-modules
            # Assign a unique version number to the modules
            rake update-pom-version
            # Exclude unnecessary modules from presto-server provisioning
            rake update-provisio-modules
            # Run mvn test-compile here to cache the compile-time dependencies
            rake compile

      - save_cache:
          paths:
            - /home/presto/.m2
            - /root/.m2
          key: presto-{{ checksum "pom.xml" }}

      - run:
          name: deploy
          command: |
            rake deploy

workflows:
  version: 2
  build_and_integration:
    jobs:
      - build_and_deploy:
          context:
            - aws-td
            - jfrog
          filters:
            tags:
              only: /.*/
